h="Hello, \nFucking World"
print(h)

#Printing my Name n Times 

x=eval(input("Enter Your Name in double quotation: "))
n=eval(input("How many time you want to print your name? "))

# Using For loops

"""
for initialize; condition; increment/decrement:
    statement
"""
print("This output is generated by For loop")

for i in range(1,n+1):
    print(i, "My Name is: ", x) 

#Using While Loops

"""
initialize
while condition:
    statement
"""
print("This output is generated by While loop")
i=1
while i <= n:
    print(i, "My Name is: ", x)
    i += 1