# -*- coding: utf-8 -*-
"""Data Frame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdEKFti9Ggm0x2jiT-gRpgnJk9_za1bq

# Pandas Data Structures:
We have learned about **Series**, lets learn DataFrames (2<sup>nd</sup> workhorse of pandas) to expand our concepts of Series.

* DataFrame
* Grab data (column wise)
* Grab data (raw wise)
* Grabbing an element or a sub-set of the dataframe
* Adding new column
* Deleting the column
* boolean_mask
* boolean_mask(Combine 2 conditions)
* reset_index(), set_index(), head(), tail(), info(), describe()

## DataFrame
* A very simple way to think about the DataFrame is, "bunch of Series together such as they share the same index". <br>
* A DataFrams is a rectangular table of data that contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc). DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index. <br>

&#9758; *A good read for those, who are interested! ([Python for Data Analysis](http://shop.oreilly.com/product/0636920023784.do))<br>*

Let's learn **DataFrame with examples:**<br>
"""

import pandas as pd
import numpy as np

"""Let's create two labels/indexes:
* for rows 'r1 to r10'
* for columns 'c1 to c10'

Let's start with a simple example, using **`arange()`** and **`reshape()`** together to create a 2D array (matrix).<br>
"""

rows = ['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']
columns = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

"""&#9989; *Use **TAB** for auto-complete and **shift + TAB**  for doc.*"""

# How the index, columns and array_2d look like!
rows

columns

array_2d = np.arange(0,100).reshape(10,10)

array_2d

df = pd.DataFrame(data = array_2d, index = rows, columns = columns)

# How the DataFrame look like!
df # select * from df

type(df)

"""**df** is our first dataframe. <br>
We have columns, c1 to c10, and their corresponding rows, r1 to r10. <br>
Each column is actually a pandas series, sharing a common index (row labels). <br>

&#9758; Let's learn how to **Grab data** that we need, this is the most important thing we want to learn to move one!<br>

### Columns
"""

df[['c1', 'c7']] #select c1, c2 from df
#df.c10

# Grabbing a single column
df[['c5']]

type(df[['c5']])

# Grabbing more than one column, pass the list of columns you need!
df[['c1', 'c10', 'c3']] #select c1, c10 from df

df['c5']   # It is a pandas Series (single [])

type(df['c5'])

"""**df.column_name (e.g. df.c1, df.c2 etc)** can be used to grab a column as well, its good to know but I don't recommend. <br>
If you press "TAB" after df., you will see lots of available methods, its good not to get confused with these option by using df.column_name.<br>
**Let's try this once**

### Adding new column
Lets try with "+" operation!
"""

df

df['new']= df['c1'] + df['c2']  # select *, (c1 + c2) as new from df

df

df['new2'] = 'A'

df

df['new3'] = [4,7,10,13,16,19,22,25,28,31]

df

"""### Deleting the column -- `drop()`

        *df.drop('new')-- ValueError: labels ['new'] not contained in axis

Shift+tab, you see the default axis is 0, which refers to the index (row labels), for column, we need to specify axis = 1.<br>
&#9758; rows refer to 0 axis and columns refers to 1 axis<br>
&#9758; Quick Check: *df.shape gives tuple (rows, cols) at [0] and [1]*
"""

# We can delete a column using drop()
# df.drop('new')# ValueError: labels ['new'] not contained in axis
df.drop('new', axis=1)      # axis=0 means row, axis=1 means column

"""&#9758; Is the "new" really deleted? <br>
Output df and you will see "new" is still there!<br>
"""

df

"""To parmanently delete the column, you have to tell the pandas by setting<br>
* ***inplace = True*** (default is inplace=False).<br>

&#9989; *pandas is generous, it does not want us to lose the information by any mistake and needs inplace*
"""

df.drop('new',axis = 1, inplace = True)
df

df.drop(columns='new2', inplace = True)
df

df.drop('new3', axis = 1, inplace = True)
df

"""### Rows
We can retrieve a row by its name or position with **[`loc`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html)** and **[`iloc`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iloc.html)**.<br>
**loc** -- Access a group of rows and columns by label(s)
"""

# df['r1'] # KeyError: 'r1'
df.loc[['r2']] # loc for location in square brackets
# we see that the rows are series as well!

"""Using row's index location with **iloc**, even if our index is labeled."""

df.iloc[[1]] # iloc[index], index based location

# more than one rows -- pass a list of rows!
df.loc[['r1', 'r2', 'r3']]

"""### Grabbing an element or a sub-set of the dataframe"""

df

df.loc['r1','c1']

df.loc[['r1','r2'],['c1','c2']]

# another example - random columns and rows in the list
df.loc[['r2','r5'],['c3','c4']]

df.loc[['r1','r7'],['c4','c4','c8']]

df

# We can do a conditional selection as well
df > 40

df

"""This is similar to NumPy boolean mask, lets try this:

    *bool_mask = df % 3 == 0
    *df[bool_mask]
returns values where it is True and NaN where False.
"""

# Return Divisible by 3
bool_mask = df % 3 == 0
bool_mask
#df[bool_mask]

"""&#9758; Its not common to use such operation on entire dataframe. We usually use them on a columns or rows instead.<br>
**For example, we don't want a row with NaN values.**<br>
What to do?<br>
Let's have a look at one example.
"""

# Our original dataframe is
df

"""Let's apply a condition on column c1, say `c1 > 11`<br>
based on the conditional selection, the out put will be:
"""

df[df['c1']>11]  # Select * from df where c1 > 11

#select c1, c3 from df where c1 > 11
df[df['c1']>11][['c1','c3']]

"""We don't want `r1` and `r2` as they return NaN or null values. <br>
Let's filter the rows based on condition on column values.
"""

df[df['c1']>11][['c3','c4','c7']]

"""&#9758; The above, **"`df[df['c1']>11]`"** is a dataframe with applied condition, we can select any col from this dataframe.<br> For example:"""

result = df[df['c1']>11]
result

"""We can do the above operations, (filtering and selecting a columns) in a single line (stack commonds).

"""

df[df['c1']>11][['c1', 'c10']]

# let's grab two columns, we need to pass the list ['c1','c9'] here
df[df['c1']>11][['c1','c9']]  #Select c1, c9 from df where c1 > 11

# We can do this operation on rows using loc
# Passing multiple rows in a list
df[df['c1']>11].loc[['r3','r4']]

result = df[df['c1']==70]
result

df

df[df['c1']==70]  #select * from df where Age == 70

"""### Combine 2 conditions
Let's try on c1 for a value > 60 and on c2 for a value > 80
"""

df

df[(df['c1']>60) & (df['c2']>80)]

"""&#9989;**NOTE:**<br>
"and" operator will not work in the above condition and using "and" will return <br>

        *ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

This "ambiguous" means, True, only work for a single booleans at a time "True and False". We need to use "&" instead. ("|" for or)<br>
Try the above code using "and" <br>
The "and" operator gets confused with series of True/False and raise Error

### Let's have a quick look on couple of useful methods.
***We will explore more later on in the course!***

**`reset_index()`** and **`set_index()`**<br>
We can reset the index of our dataframe to numerical index (which is default index), `inplace = True` to make the permanent change. *The existing index will be a new column.*
"""

df

df.reset_index(inplace = True)

df

df.set_index('c2', inplace = True)
df

df

"""** consider, We have a column in our data that could be a useful index,<br>
we want to set that column as an index!**<br>
"""

array_2d

columns

df = pd.DataFrame(data = array_2d, index = rows, columns = columns)
df

abc = 'a b c d e f g h i j'.split() # split at white spaces
# let put newind as a col in the df
df['newind']=abc
df

# setting newind as an index, needs to be inplaced
df.set_index('newind', inplace = True)

df

df = pd.DataFrame(data=array_2d, index=rows, columns=columns)
df

"""### `head()`, `tail()`"""

# Returns first n rows
df.head() # n = 5 by default

# Returns last n rows
df.tail(2) # n = 5 by default

"""### `info()`
Provides a concise summary of the DataFrame.
"""

df

df.info()

"""### `describe()`
Generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset's distribution, excluding `NaN` values.
"""

df

df.describe()

"""# Excellent!
I want to congratulate here, you are making a great progress, keep it up!
"""

df2 = pd.read_csv('E:\Breast_Cancer_Diagnostic.csv')

df2

df2.info()

df2.describe(include = 'all')

df2

pd.set_option('display.max_rows', None)

df2

df2.describe()