# -*- coding: utf-8 -*-
"""Handling_Missing_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xKzXpOS9A6qf5MILliDU5xA_M8TnVut

Hi Guys,<br>
Welcome back to the pandas essentials, now we are going to talk about the missing data!<br>
## Handling Missing Data
Missing data is very common in many data analysis applications. pandas has a great ability to deal with the missing data. <br>Let's learn some convenient methods to deal with **missing data in pandas**:<br>

* isnull(), isna(), notnull(), dropna(), fillna(),
"""

import numpy as np
import pandas as pd

data_dic = {'A':[1,2,np.nan,4,np.nan],
            'B':[np.nan,np.nan,np.nan,np.nan,np.nan],
            'C':[11,12,13,14,15],
            'E':[16,np.nan,18,19,20]}
df = pd.DataFrame(data_dic)
df

"""
**isnull(), isna(), notnull() -- Check for missing data in the dataset!**"""

df.isnull()

df.isnull().sum() #Count all null values in every columns

df.isnull().sum().sum()  #Count all null values in total dataset

df['A'].isnull()

df['A'].isnull().sum()   #Count all null values in a specific column

df.isna()     #isnull() and isna() are same

df.isna().sum().sum()

df.loc[1].isnull().sum()

df.notnull()

df.shape

df.notnull().sum()

df.notnull().sum().sum()

df

# Sum on Column "A", (NaN as 0)
df['A'].sum()

"""&#9758; NaN ignored for mean()."""

df['A'].mean()

df.loc[3].sum()

"""**dropna(), fillna() -- Cleaning / filling the missing data**"""

df.dropna(axis=1)   #Drop all columns which contains at least 1 null valaue

df.dropna(axis=0)   #Drop all rows which contains at least 1 null valaue

df

df

"""* threshold : int, default None
* thresh = 3 means, it will drop any column that have more than 3 non-NaN values.
"""

df.dropna(thresh=3, axis=1)

"""We can use fillna() to fill in the values.<br>
inplaced = True for permanent change.
"""

df.fillna(value=2)

df

"""Let's fill in the values using mean of the column."""

df['A'].fillna(value = df['A'].mean())

df

df.fillna(method='ffill')   #front fill (fill with the value of previous data)

df.fillna(method='bfill')    #back fill (fill with the value of next data)

# fill with you own given value
df.fillna(0)

df2 = df.copy()
df2

df

#Change the dataset permaently
df2.fillna(0, inplace=True)

df2

df

"""# Good Job!"""