# -*- coding: utf-8 -*-
"""Lecture 04 (User Defined Function).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QA7XGNTpslAqw0MhAynh01dtsnBkNpK9

### **Module-2**

### Functions
Two types:
1. built in function
2. user define function
"""

#Built in function
print("hello world")
print(len("hello world"))
x = max(5, 10, 16, 4)
print(x)
x = int(input())
print(x)

#User defined function
def my_function():
    print("My name is Al-Amin")
    print(36+50)

my_function()

#User defined function
def myf():
    print("My name is Al-Amin")
    print(36+50)

myf()
myf()
myf()

def add(a, b): # parameters
    print(a + b)

add(14, 8) # arguments

def add(a, b): # parameters
    print(a + b)

x = int(input("fisrt number :"))
y = int(input("second number :"))
add(x, y) # arguments

def add(a, b): # parameters
    print(f"Sum of {a} and {b} is {a+b}")

x = int(input("fisrt number :"))
y = int(input("second number :"))
add(x, y) # arguments

def myf(a, b): # parameters
  m = a + b
  n = a * b
  return m, n

x = int(input("fisrt number :"))
y = int(input("fisrt number :"))
i, j = myf(x, y) # arguments
print(i, j)

def abcd(a):
  print(f"You entered {a}")

abcd("Al-Amin")
abcd("PSHRD")
abcd("Shaon")

def fn(a, b, c) :
    print(c)

fn(10, 4, 7)

def fn(a, b, c) :
    print(c)

fn(b = 10, c = 4, a = 7)

def abcd(a):
  print("Hello " + a)

abcd("Al-Amin")
abcd("Islam")
abcd()      # Error (No argument)
abcd("PSHRD")

def abcd(a = "Not found"):
  print("Hello " + a)

abcd("Al-Amin")
abcd("Islam")
abcd()
abcd("PSHRD")

def square(a):
  return a*a

x = square(5)
print(x)

'''
This is multi line comment
Used as same as single line comment
'''
def square(a):
  '''
  Return square value
  of a number
  '''
  # doc string (a multi line comment in a function used as a doc string)
  return a*a

x = square(5)
print(x)
print(square.__doc__)   # __doc__ is an attribute (spacial command) to print doc string of a function

def add(a, b):
  return a + b

x = add(10, 20)
print(x)

"""### lambda function (annonymus function)
lambda arguments : expression
"""

x = lambda a : a * a
x(5)

x = lambda a, b: a + b
print(x(10, 20))

def fn(a):
  return lambda n : n * a

x = fn(2)      # x = lambda n : n * 2
print(x(11))

"""### map and filter function"""

marks = [78, 86, 42, 55]
def grade(marks) :
    if marks < 0 or marks > 100 :
        return 'Invalid mark'
    elif marks >= 80 :
        return 'A+'
    elif marks >= 75 :
        return 'A'
    elif marks >= 70 :
        return 'A-'
    elif marks >= 65 :
        return 'B+'
    elif marks  >= 60 :
        return 'B'
    elif marks >= 55 :
        return 'B-'
    elif marks >= 50 :
        return 'C+'
    elif marks >= 45 :
        return 'C'
    elif marks >= 40 :
        return 'D'
    else :
        return 'F'
grades = map(grade, marks)          # map(function, iterable)
                                    # iterable (on which the function will be applied)
print("Exam score : ", marks)
print("Grade : ", next(grades))     # map() is an object. next() used to apply function to one by one element
print("Grade : ", next(grades))
print("Grade : ", next(grades))

marks = [78, 14, 86, 42, 31, 55]
def grade(marks) :
    if marks < 0 or marks > 100 :
        return 'Invalid mark'
    elif marks >= 80 :
        return 'A+'
    elif marks >= 75 :
        return 'A'
    elif marks >= 70 :
        return 'A-'
    elif marks >= 65 :
        return 'B+'
    elif marks  >= 60 :
        return 'B'
    elif marks >= 55 :
        return 'B-'
    elif marks >= 50 :
        return 'C+'
    elif marks >= 45 :
        return 'C'
    elif marks >= 40 :
        return 'D'
    else :
        return 'F'
grades = map(grade, marks)          # map(function, iterable)

print("Exam score : ", marks)
print("Grade : ", list(grades))     # list() used to apply function to all element

# Without map (one element)
def fn(a):
  return len(a)

x = fn("shaon")
print(x)

# With map (all element)
def fn(a):
  return len(a)

a =  ["Apple", "banana", "jackfruit"]
x = list(map(fn,a))

print(x)

marks = [78, 14, 86, 42, 31, 55]

def fail(score) :
    return score < 40

result = filter(fail, marks)
print("Failing scores : ", list(result))

marks = [78, 14, 86, 42, 31, 55]

def fn(score):
  if score <= 40:
    return True
  else:
    return False

x = list(filter(fn,marks))
print(x)

num = [11,20,29,31,42,47,51,60,57,86]
def even(x):
    return x % 2 == 0

even = list(filter(even, num))
print("Even numbers: ", even)

num = [11,20,29,31,42,47,51,60,57,86]

even = list(filter(lambda x : x%2==0, num))
print("Even numbers: ", even)