# -*- coding: utf-8 -*-
"""Lecture 05 (Object Oriented Programming).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158tlRSPwWPYDYiglzq0KNOqR0ttpCmcn

## Module 03 (Class, Object, Method)

### Two types of programming :
**01. Structural programming**
**02. Object oriented programming**

### Class (Sceleton)
### Object (Parameter / unique characterstrics)
"""

class teacher:
    name = "Tapon Kumar Roy" # name is attribute
    age = "54"
    dept = "PSHRD"
    id = "07"

tkr = teacher()      # tkr is object snd teacher is class
print(tkr.name)      # object.attribute
print(tkr.dept)

class teacher:
    name = "Tapon Kumar Roy"
    age = "54"
    dept = "PSHRD"
    id = "07"

    def display(self):       # method (a function in class)
        print(self.name, self.dept)

tkr = teacher()
teacher.display(tkr)         # tkr.display()

class student:
    name = "Tanjeem"

student.roll = 16          # initialize attribute in every class
student1 = student()
student1.cgpa = 3.75       # initialize attribute in a specific class
print(f" Name : {student1.name}, Roll : {student1.roll}, CGPA = {student1.cgpa}")

class teacher:
  name = ""
  dept = ""
tkr = teacher()
tkr.name = "Tapon Kumar Roy"
tkr.dept = "PSHRD"
print(f"Name : {tkr.name}, Department : {tkr.dept}")

class teacher:
  name = ""
  dept = ""

  def set_values(self, v1, v2):
    self.name = v1
    self.dept = v2

  def display(self):
    print(f"Name : {self.name}, Department : {self.dept}")

sir = teacher()
sir.set_values("Tapon Kumar Roy", "PSHRD")
sir.display()

sir = teacher()
sir.set_values("Ahmed Faiyaz Rafid", "CSE")
sir.display()

class student:
    def set_value(self, roll, cgpa):
        self.roll = roll
        self.cgpa = cgpa

    def display(self):
        print(f"Roll = {self.roll}, CGPA = {self.cgpa}")

kamal = student()
kamal.set_value(10, 3.75)
kamal.display()

rashed = student()
rashed.set_value(17, 3.25)
rashed.display()

"""### Constructor (__ init __)"""

class student:
    def __init__(self):        # Default constructor
        self.name = "Al-Amin"
        self.cgpa = 3.309

    def display(self):
        print(f"Name = {self.name}, CGPA = {self.cgpa}")

student1 = student()
student1.display()

class teacher:
  def __init__(self, n, d):    # Parameterized constructor
    self.name = n
    self.dept = d

  def display(self):
    print(self.name, self.dept)

tanvir = teacher("Tanvir", "CSE")  # No need to call function like set_value() while using __init__
tanvir.display()

class teacher:
  def __init__(self, n, d, i=0):
    self.name = n
    self.dept = d
    self.id = i

  def display(self):
    print(self.name, self.dept, self.id)

tanvir = teacher("Tanvir", "CSE")
tanvir.display()
print(tanvir.name)

class teacher:
  def __init__(self, n, d, i=0):
    self.name = n
    self.dept = d
    self.id = i

  def display(self): # method
    print(f"Name = {self.name}, Department = {self.dept}, ID = {self.id}")

nabil = teacher("Nabil", "ACCE", 10)
nabil.display()
print(nabil.dept)

"""## Inheritence"""

class Person: # parent class
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(f"Name : {self.firstname} {self.lastname}")

x = Person("Al-Amin", "Islam")
x.printname()

class Student(Person): # child class (inherits person class)
    pass

y = Student("Zuhaem", "Tamim")
y.printname()

# single inheritance
class A:
    def display1(self):
        print("This is class A")

class B(A):
    def display2(self):
        print("This is class B")

objB = B()
objB.display1()
objB.display2()

# multiple inheritance
class A:
    def display1(self):
        print("This is class A")

class B:
    def display2(self):
        print("This is class B")

class C(A, B):
    def display3(self):
        print("This is class C")

objC = C()
objC.display1()
objC.display2()
objC.display3()

# multi level inheritence
class A:
    def display1(self):
        print("This is class A")

class B(A):
    def display2(self):
        print("This is class B")

class C(B):
    def display3(self):
        print("This is class C")

objC = C()

objC.display1()
objC.display2()
objC.display3()
objB.display1()

class A:
    def display1(self):
        print("This is class A")

class B(A):
    def display2(self):
        print("This is class B")

    def display1(self):
        print("This is class H")

objB = B()
objB.display2()
objB.display1()   # class B prioritize display1() in it's class first

# Hierchical inheritence
class A:
    def display1(self):
        print("This is class A")

class B(A):
    def display2(self):
        print("This is class B")

class C(A):
    def display3(self):
        print("This is class C")

class D(A):
    def display4(self):
        print("This is class D")

objB = B()
objB.display1()
objB.display2()

objC = C()
objC.display1()
objC.display3()

# objC.display2() is wrong

"""### Polymorphism"""

# Built in Polymorphic function
print(len("Al-Amin Islam"))
print(len([10, 20, 30]))
print(len((10, 20, 30, 40)))

# User define polymorphic function
def add(x, y, z=0):
    return x+y+z

print(add(30, 20))
print(add(10, 30, 20))