# -*- coding: utf-8 -*-
"""Lecture_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TemBtfjQYYeNNywr4aJJBjJzeY1SJTaM

# **Module 01 (Lecture-03)**
## **(Data structure (list, tuple, set, dictionary)**

### list (changeable, ordered, allow duplicates)
"""

my_list = [10, 20, 30, 40, 50, 'apple', "banana", 'cherry', True, 4+5j]

print(my_list)

type(my_list)

my_list = [10, 20, 30, 40, 50, 'apple', "banana", 'cherry', True, 4+5j]   # list always maintains index (order)
# f_index = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# r_index = [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1]

print(my_list[0])
print(my_list[6])
print(my_list[-5])

ls = ["apple"]
print(type(ls))
st = "apple"
print(type(st))

my_list = [10, 20, 30, 40, 50, 'apple', "banana", 'cherry', True, 4+5j]

print(my_list[0:5])      # elements from index 0 to 4
print(my_list[3:])       # elements from index 3 to the end
print(my_list[:6])       # elements from index 0 to 5
print(my_list[0:9:2])    # elements from index 0 to 8, step 2
print(my_list[-9:-4])    # from index -9 to -5
print(my_list[-9:-1:2])  # from index -9 to -2, step 2
print(my_list[::-1])     # reverse the list

lst = [5,3,0,3,9]
print(len(lst))
print(sum(lst))
print(max(lst))
print(min(lst))
print(lst*3)

ls1 = ["a", "b", "c", "m", "o"]
print(ls1 + [10, 50, "d"])

print(ls1)
print(ls1 * 3)

ls1 = ["a", "b", "c", "m", "o"]
ls1[-1] = 10     # list is changable
print(ls1)

ls1 = ["a", "b", "c", "m", "o", "a"]   # list allows duplicates
print(ls1)
len(ls1)  # length of list

ls1 = ["a", "b", "c", "m", "o"]
print(ls1)

# Removing all element permanently
ls1.clear()   # ls1 = []
print(ls1)

len(ls1)

ls2 = ["apple", "banana", "cherry", "apple", "cherry", "apple"]

print(ls2.count("apple"))  # how many times

ls1 = ["a", "b", "c", "m", 'o']

ls1.append("f")   # add an element parmanently
print(ls1)
len(ls1)

fruits = ['apple', 'banana', 'cherry']
flowers = ['rose', 'sunflower', 'lotus']

fruits.extend(flowers)  # Add all elements of 'flowers' to the end of 'fruits'
print(fruits)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

ls3.insert(3, "mango")  # Insert "mango" at index 3 permanently
print(ls3)               # Print the updated list
print(len(ls3))          # Print the length of the list

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

x = ls3.index("cherry")  # Find the index of "cherry" in the list
print(x)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

ls3.remove("cherry")   # Removes "cherry" from the list
print(ls3)             # Print the updated list
print(len(ls3))        # Print the new length of the list

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

ls3.remove(ls3[3])  # Remove the element at index 3
print(ls3)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

ls3.pop(4)   # remove element of 4th index
print(ls3)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']

ls3.pop()   # remove last element
print(ls3)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']
ls3.reverse()
print(ls3)

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']
ls3.sort() # sort in ascending order
print(ls3) # sort alphabeticaly. Capital letter first

ls3 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']
ls3.sort(reverse=True) # sort in descending order
print(ls3)

ls2 = ['apple', 'banana', 'cherry', 'rose', 'sunflower', 'lotus']
ls2[3][2]  # Access the 3rd character of the 4th element in the list

# Making a duplicate list
list1 = [1, 5, 6, 5, 1, 2, 3]
list2 = []
list2.extend(list1)
print(list1)
print(list2)  # list2 is duplicate list

"""### 2D list"""

A = [[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A =", A)

print("2nd row =", A[1])

print("A23 =", A[1][2])   # 3rd element of 2nd row
print("A13 =", A[0][-1])   # Last element of 1st Row

A = [[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

for row in A:
  print(row)

# Getting a column of the matrix
A = [[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

column = []        # empty list/row
for row in A:
  column.append(row[2])

print("3rd column =", column)

"""### Tuple (unchangeable, ordered, allow duplicates)"""

tp = ('apple', 'banana', 'cherry', 'Rose', 10, True)
print(tp[1])
print(len(tp))
print(type(tp))

fruits = ("apple", "banana", "cherry")
(var1, var2, var3) = fruits  # tuple unpacking in variables
print(var1)
print(var2)
print(var3)

tp1 = (10, 20, 4+5j, "apple", "banana", "cherry")
(var1, var2, var3, *var4) = tp1
print(var1)
print(var2)
print(var3)
print(var4)
type(var4)

my_list = [10, 20, 30, 40, 50, 'apple', "banana", 'cherry', True, 4+5j]
my_tuple = tuple(my_list)               # Converting a list to tuple
print(my_tuple)

a=(5,6)
b=(1,15)
if a>b:
    print("a is bigger")  #compare first value only
else:
    print("b is bigger")

"""### Set (unordered/unindexed, unchangeable, mutable(allow changes), don't allow duplicates)"""

my_set = {4, 3, 1, 2, 3, 4, 5, "hello", "mango"}
print(my_set)

ls = [1, 2, 3, 4, 5, 6, 7, 1, 2]
st = set(ls)
print(st)

# Set operation
set1 ={1, 2, 3, 4, 5}
set2 ={4, 5, 6, 7}

print(set1 | set2)   #union
print(set1 & set2)   #intersection
print(set1 - set2)   #difference

A = {100, 500, 300, 400}
print(A)

x = sorted(A)
print(x)
print(type(x))

A.add(600)
print(A)

A.remove(300)
print(A)

lst = list(A)
print(lst)

"""### Dictionary
key : value        paired (ordered, changeable, don't allow duplicates )
"""

mydict =	{
  "name": "Al-Amin",
  "dept": "PSHRD",
  "roll": 2110727128,
  "institute": "RU",
  "age": 23
}                               # Key : Value paired, where key is index name
print(mydict)

mydict =	{
  "name": "Al-Amin",
  "dept": "PSHRD",
  "roll": 2110727128,
  "institute": "RU",
  "age": 23
}
print(mydict["roll"])

mydict = {
    "name": "Al-Amin",
    "dept": "PSHRD",
    "roll": 2110727128,
    "institute": "RU",
    "age": 23
}

print(f"Name : {mydict['name']} \nDepartment : {mydict['dept']}")

td =	{
  "brand": ["Ford", "BMW", "Volvo"],
  "model": "Mustang",
  "year": 1964
}

print(td.get("brand"))

td =	{
  "brand": ["Ford", "BMW", "Volvo"],
  "model": "Mustang",
  "year": 1964
}

td["color"] = "white"

print(td)

td =	{
  "brand": ["Ford", "BMW", "Volvo"],
  "model": "Mustang",
  "year": 1964
}


td["color"] = "white"

# print(td)

x = td.keys()
y = td.values()
print(x)
print(y)