# -*- coding: utf-8 -*-
"""Lectures 01 & 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROZbweehvnVnrLOlR8haq8Dw3x2sdAen

#**Module 01 (Lectures 01 & 02)**
"""

# Printing a string
print("Hello world")

# Comment (Interpreter doesn't read the comment line. A single line comment starts with #)

# Variable
x = 3

# Printing the value variable
print(x)

# Printing both string and value of a variable
print("The number is", x)

print("Your provide",x,"as a number")  # Combined string and variable

# Google Colab can print any value of a variable without print() function
x

a = 50
b = "Al-Amin"
a

# But can't print multiple variable without print function. Only prints last one
a = 50
b = "Al-Amin"
a
b

# Use comma to print all without function
a = 100
b = "Jabir"
a, b

a = 89
b = "Nabil"
print(a)
print(b)
c,d = 16,36
print(c)
print(d,b)

"""### Data types"""

# Data Type

#Integer number
v1 = 5
print(type(v1))

#Floating point number
v2 = 16.28
print(type(v2))

#String
v3 = "Al-Amin"
print(type(v3))

#Boolean
v4 = True
print(type(v4))
v5 = False
print(type(v5))

#Complex number
v6 = 5+3j
print(type(v6))
print(v6.real)
print(v6.imag)

a = "Roni"
b = "Mahabub"
print(a,b)     # Printing values of more than variable

print(a+b)   #String concatenation

Name = "Al-Amin"
Inst = "Rajshahi University"
Age = 23
print("My name is " + Name + ". I read in " + Inst + ". I am " + str(Age) + " years old")  #Sting concatenation doesn't support numeric data type

"""### fstring"""

Name = "Al-Amin"
Inst = "Rajshahi University"
Age = 23
print(f"My name is {Name}. I read in {Inst}. I am {Age} years old")  # use f before the string and keep variable names in {}

"""### User Input"""

v1 = input()
v2 = input()
print(v1)
print(v2)

v1 = input()    #input() function takes only string values.
v2 = input()
print(v1+v2)    #It will concat the two values of the variable.

num1 = int(input("Enter the first number : "))
num2 = int(input("Enter the second number : "))
'''
input("......") function takes input after printing the string in "  " .
The function can input of only string data type.
int(input("Enter the first number : ")) takes input of integer data type after printing "Enter the first number : "
'''
sum = num1+num2
avg = sum/2
print("Sum of the two numbers : ", sum)
print("Average of the two numbers : ", avg)

print("The sum is",sum,"and the average is",avg)

print(f"The sum is {sum} and the average is {avg}")

"""### Arithmetic Operation"""

a = 9
b = 5

print(a+b) # Addition
print(a-b) # Subtraction
print(a*b) # Multiplication
print(a/b) # Division
print(a%b) # Modulus (Reminder)
print(a**b) # a to the power b
print(a//b) # floor division

print(10 + (3 * 2) ** 2 + 45)

"""### Math Library Function"""

import math  # call math library to access the functions
x = 2.9
print(round(x))

import math
x = 2.4
print(round(x))

x = 2.56
print(math.ceil(x))
print(math.floor(x))

math.sqrt(36)

math.pow

"""### Conditional statement"""

# Simple if Statement (Only works when the condition is true)
a = 5
if a>5 :
  print(a)       # intended to if (use 4 spaces or a tab)

a = 5
if a>=5 :
  print(a)

# if-else statement. If condition is true execute first statement, if not execute second one
a=5
if a>5 :
  print(a)       # intended to if (use 4 spaces or a tab)
else:
  print(0)       # intended to else (use 4 spaces or a tab)

a = int(input("Enter an integer number: "))
if a%2==0 :                                       # Relational operator (==, !=, <, <=, >, >=)
    print("The number is even")
else :
    print("The number is odd")

x = input("Enter your name : ")
if x == "Shaon" :
    print("You are a good boy")
else :
    print("You are a bad boy")

a = 10
b = 5

if a > b:
  print("First number is largest")
elif b > a:                            # else if
  print("Second number is largest")
else :
  print("The numbers are equal")

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

if a > b:
  print(a, "is largest")
elif b > a:                            # else if
  print(b, "is largest")
else :
  print("The numbers are equal")

# Program for spelling of a digit  (else-if ladder)

a = int(input("Enter a digit : "))
if a == 0:
  print("Zero")
elif a == 1:
  print("One")
elif a == 2:
  print("Two")
elif a == 3:
  print("Three")
elif a == 4:
  print("Four")
elif a == 5:
  print("Five")
elif a == 6:
  print("Six")
elif a == 7:
  print("Seven")
elif a == 8:
  print("Eight")
elif a == 9:
  print("Nine")
else:
  print("Not a valid digit.")

# Calculating the grade of exam from mark

mark = int(input("Enter your mark in exam : "))
if mark < 0 or mark > 100 :
    print("Invalid mark")
elif mark >= 80 :
    print("Grade : A+")
elif mark >= 75 :
    print("Grade : A")
elif mark >= 70 :
    print("Grade : A-")
elif mark >= 65 :
    print("Grade : B+")
elif mark >= 60 :
    print("Grade : B")
elif mark >= 55 :
    print("Grade : B-")
elif mark >= 50 :
    print("Grade : C+")
elif mark >= 45 :
    print("Grade : C")
elif mark >= 40 :
    print("Grade : D")
else :
    print("Grade : Fail")

"""### Logical operator (and, or, not)"""

a = 10
b = 5
c = -10

if a > b and a > c:
  print("a is largest")
elif b > a and b > c:
  print("b is largest")
else :
  print("c is larger")

a = 10
b = 10
c = -10

if a > 0 and b > 0 and c > 0:
    print("The numbers are greater than 0")
else:
    print("At least one number is not greater than 0")

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = int(input("Enter the third number: "))

if a > b and a > c:
  print(a, "is largest")
elif b > a and b > c:
  print(b, "is largest")
else :
  print(c, "is larger")

a = 10
b = 10
c = -10

if a > 0 and b > 0 and c > 0:
    print("The numbers are greater than 0")
else:
    print("At least one number is not greater than 0")

x = True
print(x)
print(not x)

y = False
print(not y)

a = int(input("Enter a number: "))

if a%3 == 0 or a%5 == 0:
    print("The number is divisible by either 3 or 5")
else:
    print("The number is not divisible by 3 or 5")

num = int(input("Enter an integer number: "))
if num>0 :
  if a%2==0 :                                       # Nasted if else statement
    print("The number is even")
  else :
    print("The number is odd")
else :
  print("Enter a positive number")

"""### Boolean (bool) data type"""

a = 9
b = 5
print(a > b)
print(a < b)
print(a == b)
print(a >= b)
print(a <= b)
print(a != b)

"""### pass statement (a null statement, which doesn’t show error)"""

x = 2
if x > 0:
  pass    # I will write code here later

def myf():
  pass

class myclass:
  pass

"""### while loop"""

i = 1  # Initialize the variable i to 1

while i <= 5:  # Condition: As long as i is less than or equal to 5, execute the loop
    print(i)  # Statement indented to indicate it's inside the loop (use 4 space or a tab)
    i = i + 1  # Increment

print("Loop ended")  # Not indented

i = 1
while i <= 5:
    print("Al-Amin")
    i += 1              # i=i+1

i = 1
while i <= 5:
    print(i,"Al-Amin")
    i += 1

i = 0
while i < 10:
  i += 1      # Increase 1 before printing
  if i == 5:
    continue
  print(i)
print("Loop ended")

i = 0
while i < 10:
  i += 2      # Increase 1 before printing
  if i == 5:
    continue
  print(i)
print("Loop ended")

i = 0
while i < 10:
  i += 1      # Increase 1 before printing
  if i == 5:
    break
  print(i)
print("Loop ended")

i = 0
while i < 10:
  i += 2      # Increase 1 before printing
  if i == 5:
    break
  print(i)
print("Loop ended")

n = int(input("Enter the value of n:"))
sum = 0
i = 1

while i <= n :
    sum = sum + i
    i = i + 1

print("1 + 2 +........+",n,"=",sum)

"""### for loop (only works on a list, range or this type data structures)"""

for i in range(6): # range(start=0, end=before 6, step=1)
  print(i)

for i in range(40,45): # range(start=40, end=before 45, step=1)
  print(i)

for i in range(16,36,6): # range(start=15, end=before 36, step=6)
  print(i)

lst = ["apple", "banana", "mango"]

for i in lst:
  print(i)

name = "Jabir"
for x in name:
    print(x)

lst = ["apple", "banana", "mango"]

for i in lst:
  for j in i: # i = apple, banana, mango
    print(j)

lst = ["apple", "banana", "mango"]

for i in lst:
  for j in i: # i = apple
    print(j)
  print(i)