# -*- coding: utf-8 -*-
"""Class09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThNHKXihGom6MzsFJ9CgH-SR7-jEVQTi
"""

#pandas import করা
import pandas as pd

#ডেটা লোড করা
df = pd.read_csv('/content/City_of_Chicago_Payroll_Data.csv')

#Dataset shape,info check
df.head()

df.shape

df.info()

#ক্লিন করা
df['Annual Salary']=df['Annual Salary'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

df['Annual Salary']

df['Hourly Rate']=df['Hourly Rate'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

df['Hourly Rate']

df.isnull().sum()

# Median দিয়ে fill করা
df['Annual Salary'].fillna(df['Annual Salary'].median(), inplace=True)
df['Hourly Rate'].fillna(df['Hourly Rate'].median(), inplace=True)
df['Typical Hours'].fillna(df['Typical Hours'].median(), inplace=True)

df.isnull().sum()

df.head()

#Full-time vs Part-time analysis
print(df['Full or Part-Time'].value_counts())

#Salary distribution
df['Annual Salary'].describe(include='all') #📌 Pandas দিয়ে Salary Distribution বোঝার উপায়

df['Annual Salary'].nunique()  #👉 কয় ধরনের ভিন্ন salary আছে

df['Annual Salary'].value_counts().head(10) #👉 কোন বেতনটা সবচেয়ে বেশি জন পাচ্ছে, তার সংখ্যা

df['Annual Salary'].max() - df['Annual Salary'].min()  #👉 সর্বোচ্চ আর সর্বনিম্ন বেতনের পার্থক্য

df['Annual Salary'].quantile([0.25, 0.5, 0.75, 0.9, 0.95])

pd.cut(df['Annual Salary'], bins=5).value_counts() #👉 এখানে বেতনের ডেটা 5 ভাগে ভাগ করবে (range বানাবে) এবং প্রতিটি range-এ কয়জন আছে তা দেখাবে।

#Department Analysis
dept_count = df['Department'].value_counts().head(10)
dept_avg_salary = df.groupby('Department')['Annual Salary'].mean().sort_values(ascending=False).head(10)
dept_avg_hourly = df.groupby('Department')['Hourly Rate'].mean().sort_values(ascending=False).head(10)

dept_avg_salary

dept_avg_hourly

#Job Titles Analysis
job_titles = df['Job Titles'].value_counts().head(10)

job_titles

df['Job Titles'].describe()

