# -*- coding: utf-8 -*-
"""Lecture 07 (Data Analysis with Pandas).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLkAOdS9XYSlW26ICgal98D0Zfv6w12D
"""

import pandas as pd

df = pd.read_csv('/content/Screen Time Data.csv')

df

df.shape

df.head()

df.head(10)

df.info()

df.columns

df['Creativity']   # pandas series

df[['Total Screen Time ']]   # pandas data frame for single column

df[['Creativity','Productivity']]     # pandas data frame for multiple columns

df.columns

df.rename(columns={'Total Screen Time ':'Screen Time'})

df.rename(columns={'Total Screen Time ':'Screen Time'}).head()

df.head()

# To change permanently use inplace=True
df.rename(columns={'Total Screen Time ':'Screen Time'}, inplace=True)

df.head()

df.drop(columns=['Date'])
#df.drop('Date',axis=1)

df.drop(columns=['Date','Week Day'])

df.head()

df.drop(columns=['index'], inplace=True)

df.head()

#Checking null values (if any)
df.isnull()
#df.isna()

#number of null values in each column
df.isnull().sum()

#Total number of null values in the dataset
df.isna().sum().sum()

# Checking null values in a specific column
df['Creativity'].isna()

#number of null values in a specific column
df['Creativity'].isnull().sum()

df['Screen Time'].max()

df['Screen Time'].min()

df['Screen Time'].mean()

df['Screen Time'].quantile(0.25)

df['Screen Time'].quantile(1)

# Descriptive statistics for all numeric columns
df.describe()

df.describe(include='all')

df.head()

# Correlation coefficient between Social Networking and Productivity
df['Social Networking'].corr(df['Productivity'])

# Correlation matrix of every numeric columns or variables
df.corr(numeric_only=True)

# Correlation matrix of specific columns or variables
df[['Screen Time','Social Networking','Productivity']].corr()

# Checking duplicate data
df.duplicated()

df.duplicated().sum()

# Dropping duplicate data
df.drop_duplicates(inplace=True)
#df.drop_duplicates()

# Sorting values in ascending order
df['Productivity'].sort_values()

# Sorting values in descending order
df['Productivity'].sort_values(ascending=False)

#Find and returns all the unique values.
df['Week Day'].unique()

# Count unique values
df['Week Day'].nunique()

df.nunique()

# Condition
df[df['Week Day']=='Friday']

df.columns

df[['Screen Time', 'Social Networking', 'Productivity']][df['Week Day']=='Friday']

#Multiple condition
df[(df['Week Day']=='Friday') & (df['Screen Time']>100)]

df[(df['Week Day']=='Friday') & (df['Screen Time']>100)][['Screen Time','Productivity']]

!pip install ydata_Profiling

from ydata_profiling import ProfileReport

# Creating a profile of the dataset
profile = ProfileReport(df, title='Screen Time Data Analysis', explorative=True)

profile

#Saving the file as html
profile.to_file('The Screen Time.html')

#Downloading the file in PC
from google.colab import files
files.download('The Screen Time.html')