# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSPml2r49aOh-ucaz8QRx3_uuuMiRLjk

Pandas is a powerful data manipulation library in Python, but it is not used in this code snippet.
It has two part
Series and DataFrame.
Series is a one-dimensional array-like object that can hold any data type.
DataFrame is a two-dimensional, size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns(Feature(Column value are known as feature value))).
"""

from google.colab import files
files.upload()

import pandas as pd

df=pd.read_csv('/content/vgsales.csv')

df1=pd.read_csv('/content/vgsales.csv')

df

from matplotlib import pyplot as plt
df['Year'].plot(kind='hist', bins=20, title='Year')
plt.gca().spines[['top', 'right',]].set_visible(False)

df.head(2)

df.tail(2)

df[5:25]

df.shape

df.columns

"""Pandas: What is does/ how it works

*   Load and Read the data
*   Can read from csv, excel, json, SQL, etc
*   Data cleaning (Missing, Duplicate rows, indexing filtering)
*Manipulation(Can Add, dlt, Merge, group, sort, aggregate add, etc)
*Data Analysis (Summarize(Mean,Sum,Count,etc)), Correlation




"""

df['Name'][10:20]

df[["Name","Platform","Publisher"]]

dnul=df.isnull().sum()

dnul

df0=df1.copy()

df.fillna(0,inplace=True)

df.isnull().sum()

df1.isnull().sum()

dic={
  "Year": 2025,
  "Publisher":"Unknown"
}

df1.fillna(dic,inplace=True)

df1.isnull().sum()

df1.info()

df0.info()

