# -*- coding: utf-8 -*-
"""Pandas df 29/08/25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGVtgT7ZMHLWUZCvnDb3-GX4a94nsKAo
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Screen Time Data.csv')

df1=df.copy

df

df.head()

df.shape

df.head(10)

df.tail(5)

df[3:6]

df.columns

df[['Yoga','Creativity']][10:20]

df.info()

"""If there exist Multiple data types: known as object"""

dnul=df.isnull().sum()

dnul

df['Total Screen Time ']

#rename
df.rename(columns={'Total Screen Time ':'Total Screen Time'},inplace=True)

"""Use inplace for true to make the replacement parmanent

"""

df.columns

#make the header all capital
df.columns=df.columns.str.upper().inplace=True

"""Dictionary is a collection which is unordered, changeable and indexed. No duplicate members.
#written with curly brackets, and have keys and values
thisdict = {
  "brand": "Ford",  
    "model": "Mustang",
    "year": 1964
}
print(thisdict)

column = feature
"""

df.drop(columns=['Date'],axis=0,inplace=True)

"""If it is a column axis = 1 if row it is 0

if you use columns= and want to omit only 1 column, you dont need axis

and if you use axis and want to omit one column you may/ may not use columns=

but if you want to omit multiple columns you must use both columns= and axis

"""

df.columns

df.drop(['Productivity','Yoga','Entertainment'],axis=1) #So if you want to delete multiple column no need to use columns= if you use axis

df['Total Screen Time'].max()

df['Total Screen Time'].mean()

df['Total Screen Time'].min()

df['Total Screen Time'].quantile(1)

df.describe()

#corelation
s=df[['Total Screen Time','Productivity','Health and Fitness','Creativity','Entertainment']].corr()

import seaborn as sns

sns.heatmap(s,annot=True)

s2 = df.select_dtypes(include=np.number).corr()
sns.heatmap(s, annot=True)



df_no_index = df.drop(columns=['index'])

# Group by 'Week Day' and calculate the mean for each category
weekly_avg_screentime = df_no_index.groupby('Week Day').mean()

# Display the result
display(weekly_avg_screentime)

"""What we need to learn...  
AI, Computer Vision, Stat mode, Tensor flow, Data modeling, Embaded Systems, predective modeling, AWS.

Primetech

Credit Earning...
"""

