# -*- coding: utf-8 -*-
"""Pandas 30.09,25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6U2oFaoGMACH5EjDdHdM5QTD65V7Fh5
"""

import pandas as pd

df=pd.read_csv('/content/Screen Time Data.csv')

df

df.info()

dfo=df.copy()

df.duplicated()

"""If there were any duplicate we had to drop duplicaate with the code

df.drop_duplicates()
"""

df.isnull()

df.columns

df.rename(columns={'Total Screen Time ' : 'Total Screen Time'},inplace=True)

df.columns

dfn=pd.read_csv('/content/emails.csv')

dfn

dfn.duplicated().sum()

fdn2=pd.read_csv('/content/data.csv')

fdn2.duplicated().sum()

fdn2.drop_duplicates(inplace=True)

fdn2.duplicated().sum()

fdn2

dfn

df['Productivity'].sort_values(ascending=True)

df['Week Day']=='Sunday'

df

df[df['Week Day']=='Thursday']

df[(df['Total Screen Time']>100) & (df['Week Day']=='Friday')]

df[(df['Total Screen Time']>100) | (df['Social Networking']>100)]

df['Week Day'].value_counts()

df[(df['Total Screen Time']>100) & (df['Social Networking']>50) & (df['Week Day']=='Friday')]

df[(df['Total Screen Time']>100) & (df['Week Day']=='Friday')]

w=df['Week Day']
type(w)

!pip install ydata_profiling

from ydata_profiling import ProfileReport as pr

profile = pr(df, title="Pandas Profiling Report by SKD")

# Display the report
profile

profile.to_file("screen_time_report.html")

profile1 = pr(df, title="Pandas Profiling Report by SKD",explorative=True)

# Display the report
profile1

profile1.to_file('The Screan Time Report.docx')

from google.colab import files
files.download('The Screan Time Report.html')

"""Data source
Kaggle
Google dataset search

# Inheritance:


1.   Hirarchical: Parent class-> Child class
2.   Multilevel :
3.   Multi
"""