# -*- coding: utf-8 -*-
"""Pandas 05.09.25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RBzlOehaFBcnIj2Brc3w5PwwIMQxFv9K
"""

import pandas as pd

df=pd.read_csv('/content/City_of_Chicago_Payroll_Data.csv')

df

df.info()

#Data cleaning
df['Annual Salary']=df['Annual Salary'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

df['Annual Salary'].head()

df['Hourly Rate']=df['Hourly Rate'].astype(str).str.replace(r'[$,]','',regex=True).replace('nan',None).astype(float)

df['Hourly Rate'].head()

df.isnull().sum()

df['Annual Salary'].fillna(df['Annual Salary'].median(),inplace=True)

df['Typical Hours'].fillna(df['Typical Hours'].median(),inplace=True)

df['Hourly Rate'].fillna(df['Hourly Rate'].median(),inplace=True)

df.isnull().sum()

df.head()

df['Full or Part-Time'].value_counts()

df['Salary or Hourly'].value_counts()

df['Annual Salary'].describe()

df['Department'].describe()

df['Department'].describe(include='all')

df['Job Titles'].describe(include='all')

df['Job Titles'].describe()

df['Department'].value_counts().head(10)

df['Annual Salary'].value_counts().head(10)

df['Department'].value_counts(df['Annual Salary'].mean()).head(10)

df.groupby('Department')['Annual Salary'].mean().sort_values(ascending=False).head(10)

df['Job Titles'].value_counts().head(10)

df.groupby('Department')['Hourly Rate'].mean().sort_values(ascending=True).head(10)

df['Annual Salary'].nunique()



!pip install ydata_profiling

from ydata_profiling import ProfileReport as pr

profile = pr(df[['Annual Salary','Department','Hourly Rate']], title="Pandas Profiling Report by SKD",explorative=True)

# Display the report
profile

profile.to_file('Dept Salary.html')
from google.colab import files
files.download('Dept Salary.html')

