# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fb-7GUoAp6LWvbYW6T6F1beQauBzw_BX

Q1. Create a class Student with attributes: name, roll, and marks.

• Add a method display() to print the student’s details.

• Create two objects and display their information.
"""

class Student:
     def __init__(self, name, roll, dept):
      self.name = name
      self.roll =roll
      self.dept= dept

     def display(self):
      print("Name: ", self.name, "\nRoll: ", self.roll, "\nDepartment: ", self.dept)

S1=Student("Soumitro", "49", "Applied Mathematics")
S1.display()
S2=Student("Tithy", "47", "Food and Nutritional Science")
S2.display()

"""Q2. Write a program where:


• Class A has method display1().


• Class B inherits from Class A and adds method display2().

• Class C inherits from Class B and adds method display3().

• Create an object of Class C and call all three methods.
"""

class A:
  def display1(self):
    print("This is in the vast universe")
class B(A):
  def display2(self):
    print("This is in the cosmos")
class C(B):
  def display3(self):
    print("This is the earth")

Earth=C()
Earth.display3()
Earth.display2()
Earth.display1()

"""Q3. Create a pandas DataFrame from a dictionary containing the following data:

Name Age Marks

Alice 20 85

Bob 22 90

Carol 21 78

David 23 88

Eve 19 65

Display the DataFrame.
"""

import pandas as pd

Sdata = {
   'Name': ['Alice','Bob','Carol','David','Eve'],
   'Age' : [20,22,21,23,19],
   'Marks': [85,90,78,88,65]
 }

St=pd.DataFrame(Sdata)

St

St = St.sort_values(by='Marks', ascending=True)

St

"""Q4. From the DataFrame in Q3:
1. Find all rows where Age > 21.
2. Find names of students who scored Marks ≥ 85.
3. Using pandas, find the Age and Marks of the student named David.
"""

St[St['Age']>21]

St[['Name','Marks']][St['Marks']>85]

St[St['Name'] == 'David']

"""Q5. Using the DataFrame in Q3, find:

• The average (mean) marks.

• The maximum marks.

• The minimum marks.

• The minimum age.
"""

St.info()

St['Marks'].mean()

St['Marks'].max()

St['Marks'].min()

St['Age'].min()

