# -*- coding: utf-8 -*-
"""Seaborn 14_09_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh6t7j02Y0KjznzwWj9TLrW45ZKy_VzX
"""

import seaborn as sns

"""Seaborn has some built-in data sets you can load directly"""

df=sns.load_dataset('tips')
df1=df.copy

df

df.info()

!pip install ydata_profiling

from ydata_profiling import ProfileReport as pr

profile = pr(df, title="Pandas Profiling Report by SKD",explorative=True)

# Display the report
profile

sns.histplot(df['total_bill'],kde=True,color='orange',bins=20)

"""If you want to castomize the whole thing, use matplotlib, if you want it fast then seaborn"""

sns.barplot(df['smoker']) # Catagorical column

sns.barplot(x='day',y='total_bill',data=df, hue='sex') #catagory, conituous

sns.barplot(df['day'])

"""Boxplot will determine if you have outlier or not"""

sns.boxplot(x='day',y='total_bill',data=df, hue='sex')

"""here top bar is the maz, lowest bar is the min... mid bar inside the box is the median and bottop apart of the box is the first quartile and upper one is 2nd quartile"""

import matplotlib.pyplot as plt
sns.violinplot(x='day',y='total_bill',data=df, hue='sex')
plt.title('Total Bill by Day')

sns.catplot(x='day',y='total_bill',data=df, hue= 'sex', kind='bar')

sns.catplot(x='day',y='total_bill',data=df, hue= 'sex', kind='strip')

sns.catplot(x='day',y='total_bill',data=df, hue= 'sex', kind='point')

sns.catplot(x='day',y='total_bill',data=df, hue= 'sex', kind='boxen')

sns.catplot(x='day',y='total_bill',data=df, hue= 'sex', kind='swarm')

sns.catplot(df['day'], kind='count') #in count plot you just put the catagorical variable not anything else

sns.pairplot(df)

p=sns.PairGrid(df)
p.map_diag(sns.histplot)
p.map_upper(sns.scatterplot)
p.map_lower(sns.kdeplot)

p=sns.PairGrid(df)
p.map_diag(sns.kdeplot)
p.map_upper(sns.scatterplot)
p.map_lower(sns.histplot)

sns.lmplot(x='total_bill',y='tip',data=df, hue='sex', markers=['|','o']) #to have the regressional line

sns.lmplot(x='total_bill',y='tip',data=df, hue='sex', col='sex', markers=['|','o'])
sns.set_style('darkgrid')

import plotly.express as px #

fig=px.pie(df,values='total_bill',names='day',title='Total Bill by Day',hole=0.5)
fig.show()

fig = px.pie(df, values='total_bill', names='day', title='Total Bill by Day', hole=0.5, pulled=[0.2 if day == 'Sun' else 0 for day in df['day'].unique()])
fig.show()

pulled_values = [0.2 if day == 'Sun' else 0 for day in df['day']]

fig = px.pie(df, values='total_bill', names='day', title='Total Bill by Day', hole=0.5, pulled=pulled_values)
fig.show()

import plotly.graph_objects as go

fig = go.Figure(data=[go.Pie(labels=df['day'], values=df['total_bill'], hole=0.5, pull=[0.2 if day == 'Sun' else 0 for day in df['day']])])
fig.update_layout(title_text='Total Bill by Day')
fig.show()

a=df.corr(numeric_only=True)
a

sns.heatmap(a, annot=True, cmap='Blues', linewidth=0.2) #annotation helps you to put values inside the box

