# -*- coding: utf-8 -*-
"""cl 11 Matplotlib 08_09_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh_to-HU1Lfolzt-CQne5VpM2rXU5j3X
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""It is numeric python

3 type of arrey: 1d,2d(metrix),3d(tensor)

arrey will have same types of data
"""

import numpy as np

np.random.seed(42)
#Here seed will fix your generated rendom values
X=np.random.randn(20)
Y=np.random.randn(20)

X

Y

plt.scatter(X,Y, color='r', marker='o', s=100)
plt.xlabel('X')
plt.xlabel('Y')
plt.show()

Catories=['AI','ML','DL','Data Analysis']
student=[20,30,40,50]
color=['red','blue','orange','yellow']

plt.figure(figsize=(10,5))
'''Here the size in inch & has to define before plotting or else will create different canvas'''
plt.bar(Catories,student, color=color)
plt.xlabel('Catories')
plt.ylabel('student')
plt.title('Bar Chart')
plt.show()

plt.figure(figsize=(16,9)) #it will not work as we are using different variables fig and ax
fig,ax=plt.subplots()
'''Its a constructor
Here fig, ax ae the api and in the backend it is running for loops to put selct the bars and their values and then putting the value in the top
here fig and ax are multiple variable with same atribute subplot()
/
here already class is there in matplotlib namely subplots and we are definig fig and ax as the object and thats why need to call the object for the class to work'''
bars=ax.bar(Catories,student, color=color)
ax.bar_label(bars)
plt.xlabel('Catories')
plt.ylabel('student')
plt.title('Bar Chart')
plt.show()

fig,ax=plt.subplots(figsize=(16,9))
bars=ax.bar(Catories,student, color=color)
ax.bar_label(bars)
ax.set_xlabel('Catories')
ax.set_ylabel('student')
ax.set_title('Bar Chart',size=20, color='r')
plt.show()

fig,ax=plt.subplots(figsize=(16,9))
bars=ax.barh(Catories,student, color=color, height=0.5)
ax.bar_label(bars)
ax.set_ylabel('Catories')
ax.set_xlabel('student')
ax.set_title('Bar Chart',size=20, color='r')
plt.show()

"""Histogram= Needed for probability distribution (for normal destribution, mean median and mode will be same and in the middle)"""

np.random.seed(42)
data=np.random.randn(2000)
plt.hist(data,bins=50, color='g',edgecolor='red') #bin means the range for each bars (dx), and edgecolor used to separate the bins
plt.title("Histogram: Normal distribution")
plt.show()

Course=['Python','C++','Fortran','Mathematica','MATLAB']
Students=[20,30,40,50,60]
plt.pie(Students, labels=Course, autopct='%1.2f%%') #auto percentage== autopct 1=100 and .2=how many places to take after .
plt.show()

explodes=[0,0,0,0.1,0] # explodes will extract one part of the pie (position of the value will corresponed with the course list)
Course=['Python','C++','Fortran','Mathematica','MATLAB']
Students=[20,30,40,50,60]
plt.pie(Students, labels=Course, autopct='%1.2f%%',explode=explodes)
plt.legend(bbox_to_anchor=(-0.1,0.7),shadow=True)
plt.title('Students Distribution')
plt.show()

explodes=[0.05,0.05,0.05,0.05,0.05]
Course=['Python','C++','Fortran','Mathematica','MATLAB']
Students=[20,30,40,50,60]
plt.pie(Students, labels=Course, autopct='%1.2f%%',explode=explodes)
plt.legend(bbox_to_anchor=(-0.1,0.7),shadow=True)
plt.title('Students Distribution')
plt.show()

